package kre18_lab03;

public class Form3 extends javax.swing.JFrame {

    public Form3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_random = new javax.swing.JButton();
        jButton_otvet = new javax.swing.JButton();
        jLabel_mytask = new javax.swing.JLabel();
        jLabel_otvet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Лабораторная 3");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getResource("/kre18_lab03/logo.png")));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                { new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                { new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                { new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCellSelectionEnabled(true);
        jTable1.setGridColor(new java.awt.Color(51, 51, 255));
        jTable1.setMaximumSize(new java.awt.Dimension(75, 120));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 51));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jTable1.setTableHeader(null);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 260, 123);

        jButton_random.setText("<html><p align=\"center\">Заполнить таблицу случайными числами<p></html>");
        jButton_random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_randomActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_random);
        jButton_random.setBounds(280, 180, 120, 70);

        jButton_otvet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kre18_lab03/otvet.png"))); // NOI18N
        jButton_otvet.setText("Ответ");
        jButton_otvet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_otvetActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_otvet);
        jButton_otvet.setBounds(280, 260, 120, 34);

        jLabel_mytask.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_mytask.setText("<html>\n<p align=\"center\">Найти максимальный элемент второй строки.\nЕсли он больше первого элемента третьей строки, то поменять элементы местами</p>\n</html>");
        jLabel_mytask.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel_mytask);
        jLabel_mytask.setBounds(0, 0, 400, 100);

        jLabel_otvet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "тут будет ответ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(jLabel_otvet);
        jLabel_otvet.setBounds(0, 120, 400, 50);

        setSize(new java.awt.Dimension(411, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_randomActionPerformed
        // Случайные числа
        int i = 0;
        while (i < jTable1.getRowCount()) {
            int j = 0;
            while (j < jTable1.getColumnCount()) {
                jTable1.setValueAt(Math.round(Math.random() * 100), i, j);
                j++;
            }
            i++;
        }
    }//GEN-LAST:event_jButton_randomActionPerformed

    private void jButton_otvetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_otvetActionPerformed
        /* инициализация переменных */
        int i = 1; // 2-я строка, отсчёт от 0        
        int max = Integer.parseInt(jTable1.getValueAt(i, 0).toString());
        int x = Integer.parseInt(jTable1.getValueAt(2, 0).toString());
        byte count = 0;
        /* само задание */
        int j = 0;
        while (j < jTable1.getColumnCount()) {
            if (Integer.parseInt(jTable1.getValueAt(i, j).toString()) == max) {
                count++;
            }
            if (Integer.parseInt(jTable1.getValueAt(i, j).toString()) > max) {
                max = Integer.parseInt(jTable1.getValueAt(i, j).toString());
            }
            j++;
        }
        if (max > x) {
            j = 0;
            while (j < jTable1.getColumnCount()) {
                if (Integer.parseInt(jTable1.getValueAt(i, j).toString()) == max) {
                    jTable1.setValueAt(x, i, j);
                }
                j++;
            }

            jTable1.setValueAt(max, 2, 0);
        }
        jLabel_otvet.setText(String.valueOf(x));
    }//GEN-LAST:event_jButton_otvetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_otvet;
    private javax.swing.JButton jButton_random;
    private javax.swing.JLabel jLabel_mytask;
    private javax.swing.JLabel jLabel_otvet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
