public class Form3 extends javax.swing.JFrame {

    public Form3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_random = new javax.swing.JButton();
        jButton_otvet = new javax.swing.JButton();
        jLabel_mytask = new javax.swing.JLabel();
        jLabel_otvet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Лабораторная 3");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getResource("logo.png")));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "0", "0", "0", "0"},
                {"0", "0", "0", "0", "0"},
                {"0", "0", "0", "0", "0"},
                {"0", "0", "0", "0", "0"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(51, 51, 255));
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.setTableHeader(null);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 260, 123);

        jButton_random.setText("<html><p align=\"center\">Заполнить таблицу случайными числами<p></html>");
        getContentPane().add(jButton_random);
        jButton_random.setBounds(280, 180, 120, 70);

        jButton_otvet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otvet.png"))); // NOI18N
        jButton_otvet.setText("Ответ");
        getContentPane().add(jButton_otvet);
        jButton_otvet.setBounds(280, 260, 120, 34);

        jLabel_mytask.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_mytask.setText("<html>\n<p align=\"center\">Найти максимальный элемент второй строки.\nЕсли он больше первого элемента третьей строки, то поменять элементы местами</p>\n</html>");
        jLabel_mytask.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel_mytask);
        jLabel_mytask.setBounds(0, 0, 400, 100);

        jLabel_otvet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "тут будет ответ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(jLabel_otvet);
        jLabel_otvet.setBounds(0, 120, 400, 50);

        setSize(new java.awt.Dimension(411, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_otvet;
    private javax.swing.JButton jButton_random;
    private javax.swing.JLabel jLabel_mytask;
    private javax.swing.JLabel jLabel_otvet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
